platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'Mantle', '~> 2.0.4'
pod 'XHImageViewer'
pod 'SDCycleScrollView', '~> 1.3'
pod 'MJExtension', '~> 2.5.7'
pod 'MJRefresh', '~> 2.4.7'
pod 'XLForm', '~> 3.0.2'
pod 'MLPhotoBrowser', '~> 0.5.0'
pod 'MJPhotoBrowser', '~> 1.0.2'
pod 'RongCloudIMKit', '~> 2.3.0'
pod 'FMDB', '~> 2.5'
pod 'TAlertView', '~> 0.2.0'
pod 'WechatShortVideo'